"""Shared pieces of the financial models (ADR-015).

The ledger tables never let the application choose their id: `id` has only a server default (no
Python-side uuid4), because the application role has no INSERT privilege on `id` columns of
financial tables (a client-chosen id could collide with a row of another tenant and reveal it).
"""

import uuid

from sqlalchemy import ForeignKeyConstraint, Uuid, text
from sqlalchemy.orm import Mapped, mapped_column

HEX64 = "^[0-9a-f]{64}$"
KINDS = ("CONTRIBUTION", "EXPENSE", "REIMBURSEMENT", "REFUND")


def fin_pk() -> Mapped[uuid.UUID]:
    """Primary key generated by the database only."""
    return mapped_column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))


def in_list(column: str, values: tuple[str, ...]) -> str:
    return f"{column} IN ({', '.join(repr(value) for value in values)})"


class ScopeMixin:
    """Every financial table belongs to an organization and a school (the tenant of ADR-014)."""

    organization_id: Mapped[uuid.UUID] = mapped_column(Uuid)
    school_id: Mapped[uuid.UUID] = mapped_column(Uuid)


def scope_constraints(table: str) -> tuple[ForeignKeyConstraint, ForeignKeyConstraint]:
    """The organization FK and the composite (school_id, organization_id) FK to schools."""
    return (
        ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=f"fk_{table}_organization_id_organizations",
            ondelete="RESTRICT",
        ),
        ForeignKeyConstraint(
            ["school_id", "organization_id"],
            ["schools.id", "schools.organization_id"],
            name=f"fk_{table}_school_id_organization_id_schools",
            ondelete="RESTRICT",
        ),
    )


def user_fk(table: str, column: str) -> ForeignKeyConstraint:
    """A single-column FK to users: guarded by the assert_active_member trigger (see 0007)."""
    return ForeignKeyConstraint(
        [column], ["users.id"], name=f"fk_{table}_{column}_users", ondelete="RESTRICT"
    )


def detail_fk(table: str) -> ForeignKeyConstraint:
    """A detail row points at ITS ledger row: same school and the declared kind."""
    return ForeignKeyConstraint(
        ["transaction_id", "organization_id", "school_id", "kind"],
        [
            "financial_transactions.id",
            "financial_transactions.organization_id",
            "financial_transactions.school_id",
            "financial_transactions.kind",
        ],
        name=f"fk_{table}_transaction_id_financial_transactions",
        ondelete="RESTRICT",
    )
