# ruff: noqa: E501, S608  (SQL text)
"""Condition 7: with about 100 thousand movements the statement and the closing use the index.

The data is generated by SQL in the throwaway database of the session (never the development one):
20 schools of 5 thousand movements over two years (contributions, expenses of the APM and of
collaborators, reimbursements, refunds). The plans are read from the server itself with
auto_explain (nested statements, because the statement functions hide their query), and a plan with
a sequential scan of the ledger or of the expenses fails the test.
"""

import time
import uuid
from collections.abc import Iterator
from dataclasses import dataclass
from typing import Any

import pytest
from sqlalchemy import Connection, Engine, create_engine, text

from tests.dbsupport import ScratchDb

SCHOOLS = 20
PER_SCHOOL = 5000  # 3000 contributions, 1500 expenses (1 in 6 by a collaborator), 250 + 250
TOTAL = SCHOOLS * PER_SCHOOL


@dataclass(frozen=True)
class PerfData:
    engine: Engine
    org: uuid.UUID
    schools: list[uuid.UUID]
    user: uuid.UUID


@pytest.fixture(scope="module")
def perf(migrated_scratch_db: ScratchDb) -> Iterator[PerfData]:
    engine = create_engine(migrated_scratch_db.admin_url)
    org, user = uuid.uuid4(), uuid.uuid4()
    schools: list[uuid.UUID] = []
    with engine.begin() as conn:
        conn.execute(
            text("INSERT INTO organizations (id, name, slug) VALUES (:o, 'Perf', :s)"),
            {"o": org, "s": f"perf-{org.hex[:10]}"},
        )
        conn.execute(
            text("INSERT INTO users (id, email, full_name) VALUES (:u, :e, 'Perf user')"),
            {"u": user, "e": f"perf-{org.hex[:10]}@example.test"},
        )
        conn.execute(
            text(
                "INSERT INTO memberships (user_id, organization_id, school_id, role, status) "
                "VALUES (:u, :o, NULL, 'organization_admin', 'active')"
            ),
            {"u": user, "o": org},
        )
        for i in range(SCHOOLS):
            school = uuid.uuid4()
            schools.append(school)
            conn.execute(
                text(
                    "INSERT INTO schools (id, organization_id, name, slug) VALUES (:s, :o, 'S', :slug)"
                ),
                {"s": school, "o": org, "slug": f"perf-{i}-{org.hex[:10]}"},
            )
    with engine.begin() as conn:
        conn.execute(
            text("SET LOCAL session_replication_role = replica")
        )  # bulk load: triggers off
        for school in schools:
            category, category_in = uuid.uuid4(), uuid.uuid4()
            for cid, key, applies_to, group in (
                (category, "perf_out", "OUT", "EXPENSES_REIMBURSEMENTS"),
                (category_in, "perf_in", "IN", "CONTRIBUTIONS"),
            ):
                conn.execute(
                    text(
                        "INSERT INTO categories (id, organization_id, school_id, key, name, "
                        "applies_to, report_group) VALUES (:c, :o, :s, :k, :k, :a, :g)"
                    ),
                    {"c": cid, "o": org, "s": school, "k": key, "a": applies_to, "g": group},
                )
            params = {"o": org, "s": school, "c": category, "ci": category_in, "u": user}
            spread = "timestamptz '2024-01-01 12:00+00' + random() * 700 * interval '1 day'"
            conn.execute(
                text(
                    "INSERT INTO financial_transactions (organization_id, school_id, kind, direction, "
                    "amount_cents, status, category_id, origin_type, occurred_at, settled_at, "
                    "reference_code) "
                    "SELECT :o, :s, 'CONTRIBUTION', 'IN', 100 + g % 900, 'PAID', :ci, 'GUARDIAN', "
                    f"ts, ts, g "
                    f"FROM (SELECT g, {spread} AS ts FROM generate_series(1, 3000) g) x"
                ),
                params,
            )
            conn.execute(
                text(
                    "WITH x AS (SELECT gen_random_uuid() AS id, g, "
                    + spread
                    + " AS ts FROM generate_series(3001, 4500) g), "
                    "ins AS (INSERT INTO financial_transactions (id, organization_id, school_id, kind, direction, "
                    "amount_cents, status, category_id, origin_type, occurred_at, settled_at, "
                    "created_by_user_id, reference_code) "
                    "SELECT id, :o, :s, 'EXPENSE', 'OUT', 50 + g % 500, 'PAID', :c, 'TEACHER', ts, ts, :u, g "
                    "FROM x RETURNING id) "
                    "INSERT INTO expenses (transaction_id, organization_id, school_id, description, paid_by, "
                    "submitted_by_user_id) SELECT x.id, :o, :s, 'Material', "
                    "CASE WHEN x.g % 6 = 0 THEN 'COLLABORATOR' ELSE 'APM' END, :u FROM x"
                ),
                params,
            )
            conn.execute(
                text(
                    "INSERT INTO financial_transactions (organization_id, school_id, kind, direction, "
                    "amount_cents, status, category_id, origin_type, occurred_at, settled_at, "
                    "created_by_user_id, parent_transaction_id, parent_kind, reference_code) "
                    "SELECT :o, :s, 'REIMBURSEMENT', 'OUT', 70, 'PAID', :c, 'TEACHER', ts, ts, :u, "
                    f"gen_random_uuid(), 'EXPENSE', g "
                    f"FROM (SELECT g, {spread} AS ts FROM generate_series(4501, 4750) g) x"
                ),
                params,
            )
            conn.execute(
                text(
                    "INSERT INTO financial_transactions (organization_id, school_id, kind, direction, "
                    "amount_cents, status, category_id, origin_type, occurred_at, settled_at, "
                    "created_by_user_id, parent_transaction_id, parent_kind, reference_code) "
                    "SELECT :o, :s, 'REFUND', 'IN', 30, 'CONFIRMED', :ci, 'TEACHER', ts, ts, :u, "
                    f"gen_random_uuid(), 'EXPENSE', g "
                    f"FROM (SELECT g, {spread} AS ts FROM generate_series(4751, 5000) g) x"
                ),
                params,
            )
        # The detail rows the statement joins to (a real ledger has one per contribution, per
        # reimbursement and per refund), so the planner sees tables of a realistic size.
        for table, kind in (
            ("contributions", "CONTRIBUTION"),
            ("reimbursements", "REIMBURSEMENT"),
            ("refunds", "REFUND"),
        ):
            extra = {
                "contributions": ", method",
                "reimbursements": ", beneficiary_user_id",
                "refunds": ", reason",
            }[table]
            values = {
                "contributions": ", 'CASH'",
                "reimbursements": ", :u",
                "refunds": ", 'devolucao'",
            }[table]
            conn.execute(
                text(
                    f"INSERT INTO {table} (transaction_id, organization_id, school_id{extra}) "
                    f"SELECT id, organization_id, school_id{values} FROM financial_transactions "
                    "WHERE organization_id = :o AND kind = :k"
                ),
                {"o": org, "k": kind, "u": user},
            )
    with engine.connect().execution_options(isolation_level="AUTOCOMMIT") as conn:
        for table in (
            "financial_transactions",
            "expenses",
            "contributions",
            "reimbursements",
            "refunds",
            "categories",
        ):
            conn.exec_driver_sql(f"ANALYZE {table}")
    yield PerfData(engine, org, schools, user)
    engine.dispose()


def explain_nested(conn: Connection, sql: str, params: dict[str, Any]) -> tuple[str, float]:
    """Run `sql` and return (the plans of every statement it ran, seconds), read from the server."""
    messages: list[str] = []
    raw: Any = conn.connection.dbapi_connection
    raw.add_notice_handler(lambda diag: messages.append(str(diag.message_primary)))
    conn.exec_driver_sql("LOAD 'auto_explain'")
    conn.exec_driver_sql("SET auto_explain.log_min_duration = 0")
    conn.exec_driver_sql("SET auto_explain.log_nested_statements = on")
    conn.exec_driver_sql("SET client_min_messages = log")
    started = time.perf_counter()
    result = conn.execute(text(sql), params)
    if result.returns_rows:
        result.all()
    elapsed = time.perf_counter() - started
    conn.exec_driver_sql("SET client_min_messages = notice")
    return "\n".join(messages), elapsed


def assert_indexed(plans: str) -> None:
    assert "plan:" in plans, "no plan was captured: auto_explain did not report"
    assert "Seq Scan on financial_transactions" not in plans, plans
    assert "Seq Scan on expenses" not in plans, plans
    for detail in ("contributions", "reimbursements", "refunds"):
        assert f"Seq Scan on {detail}" not in plans, plans
    assert (
        "ix_financial_transactions_school_settled" in plans
        or "ix_financial_transactions_school_status" in plans
    ), plans


def test_the_data_set_has_a_hundred_thousand_movements(perf: PerfData) -> None:
    with perf.engine.connect() as conn:
        assert (
            conn.execute(
                text("SELECT count(*) FROM financial_transactions WHERE organization_id = :o"),
                {"o": perf.org},
            ).scalar_one()
            == TOTAL
        )
        assert (
            conn.execute(
                text(
                    "SELECT count(DISTINCT school_id) FROM financial_transactions WHERE organization_id = :o"
                ),
                {"o": perf.org},
            ).scalar_one()
            == SCHOOLS
        )


@pytest.mark.parametrize(
    ("name", "sql", "seconds"),
    [
        (
            "entries of a month",
            "SELECT * FROM statement_entries(:s, '2025-03-01', '2025-03-31')",
            1.0,
        ),
        (
            "summary of a month",
            "SELECT * FROM statement_summary(:s, '2025-03-01', '2025-03-31')",
            1.0,
        ),
        (
            "summary of the last month with an old opening",
            "SELECT * FROM statement_summary(:s, '2025-11-01', '2025-11-30')",
            1.0,
        ),
        ("hash of a month", "SELECT closing_entries_hash(:s, '2025-03-01', '2025-03-31')", 2.0),
        ("pending", "SELECT * FROM statement_pending(:s)", 1.0),
    ],
)
def test_the_statement_uses_the_index_and_is_fast(
    perf: PerfData, name: str, sql: str, seconds: float
) -> None:
    with perf.engine.connect() as conn:
        plans, elapsed = explain_nested(conn, sql, {"s": perf.schools[0]})
    assert_indexed(plans)
    print(f"PERF {name}: {elapsed * 1000:.1f} ms")
    assert elapsed < seconds, f"{name} took {elapsed:.2f}s"


def test_closing_a_month_uses_the_index_and_is_fast(perf: PerfData) -> None:
    with perf.engine.connect() as conn:
        transaction = conn.begin()
        plans, elapsed = explain_nested(
            conn,
            "INSERT INTO monthly_closings (organization_id, school_id, period_start, closed_by_user_id) "
            "VALUES (:o, :s, '2024-02-01', :u)",
            {"o": perf.org, "s": perf.schools[1], "u": perf.user},
        )
        transaction.rollback()
    assert_indexed(plans)
    print(f"PERF closing a month: {elapsed * 1000:.1f} ms")
    assert elapsed < 3.0, f"closing took {elapsed:.2f}s"


def test_the_reference_code_lookup_and_the_booking_use_indexes(perf: PerfData) -> None:
    """max(reference_code) walks the (school_id, reference_code) index; the booking reads the closings by school."""
    with perf.engine.connect() as conn:
        transaction = conn.begin()
        plans, elapsed = explain_nested(
            conn,
            "INSERT INTO financial_transactions (organization_id, school_id, kind, direction, amount_cents, "
            "status, category_id, origin_type) VALUES (:o, :s, 'CONTRIBUTION', 'IN', 100, "
            "'PENDING_PAYMENT', (SELECT id FROM categories WHERE school_id = :s AND key = 'perf_in'), 'GUARDIAN')",
            {"o": perf.org, "s": perf.schools[2]},
        )
        transaction.rollback()
    assert "Seq Scan on financial_transactions" not in plans, plans
    assert "uq_financial_transactions_school_id_reference_code" in plans, plans
    assert elapsed < 1.0
